export const EDIT_PROJECTS="EDIT_PROJECTS"

export const EDIT_PROJECTS_REQUEST="EDIT_PROJECTS_REQUEST"
export const EDIT_PROJECTS_SUCCESS="EDIT_PROJECTS_SUCCESS"
export const EDIT_PROJECTS_FAILURE="EDIT_PROJECTS_FAILURE"