export const ADD_HOLIDAYS="ADD_HOLIDAYS"

export const ADD_HOLIDAYS_REQUEST="ADD_HOLIDAYS_REQUEST"
export const ADD_HOLIDAYS_SUCCESS="ADD_HOLIDAYS_SUCCESS"
export const ADD_HOLIDAYS_FAILUER="ADD_HOLIDAYS_FAILUER"