export const VIEW_EMPLOYEE_DETAILS="VIEW_EMPLOYEE_DETAILS"

export const VIEW_EMPLOYEE_REQUEST="VIEW_EMPLOYEE_REQUEST"
export const VIEW_EMPLOYEE_SUCCESS="VIEW_EMPLOYEE_SUCCESS"
export const VIEW_EMPLOYEE_FAILUER="VIEW_EMPLOYEE_FAILUER"