export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const ADD_EMPLOYEE_EDUCATION="ADD_EMPLOYEE_EDUCATION"
export const ADD_EMPLOYEE_EXPERIENCE="ADD_EMPLOYEE_EXPERIENCE"
export const ADD_EMPLOYEE_PROJECT="ADD_EMPLOYEE_PROJECT"
export const ADD_EMPLOYEE_BANK="ADD_EMPLOYEE_BANK"

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST"
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS"
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE"
export const CHANGE_STEP_VALUE    = "CHANGE_STEP_VALUE";

export const ADD_EDUCATION_REQUEST = "ADD_EDUCATION_REQUEST"
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS"
export const ADD_EDUCATION_FAILURE = "ADD_EDUCATION_FAILURE"

export const ADD_EXPERIENCE_REQUEST="ADD_EXPERIENCE_REQUEST"
export const ADD_EXPERIENCE_SUCCESS="ADD_EXPERIENCE_SUCCESS"
export const ADD_EXPERIENCE_FAILURE="ADD_EXPERIENCE_FAILURE"

export const ADD_PROJECT_REQUEST="ADD_PROJECT_REQUEST"
export const ADD_PROJECT_SUCCESS="ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAILURE="ADD_PROJECT_FAILURE"

export const ADD_BANK_REQUEST="ADD_BANK_REQUEST"
export const ADD_BANK_SUCCESS="ADD_BANK_SUCCESS"
export const ADD_BANK_FAILURE="ADD_BANK_FAILURE"