export const DELETE_HOLIDAY="DELETE_HOLIDAY"

export const DELETE_HOLIDAY_REQUEST="DELETE_HOLIDAY_REQUEST"
export const DELETE_HOLIDAY_SUCCESS="DELETE_HOLIDAY_SUCCESS"
export const DELETE_HOLIDAY_FAILURE="DELETE_HOLIDAY_FAILURE"