export const EDIT_CLIENT="EDIT_CLIENT"

export const EDIT_CLIENT_REQUEST="EDIT_CLIENT_REQUEST"
export const EDIT_CLIENT_SUCCESS="EDIT_CLIENT_SUCCESS"
export const EDIT_CLIENT_FAILURE="EDIT_CLIENT_FAILURE"