import EmpFormModel from "./EmpFormModel";
const {
  formField: {
    basicDetails: {
      name,
      username,
      emp_id,
      designation,
      date_of_joining,
      image,
      mobile,
      email,
      password,
      company_email,
      company_email_password,
      skype_account,
      skype_password,
      home_number,
      assign_role,
      date_of_birth,
      aadhar_card,
      aadhar_image,
      aadhar_image_back,
      pan_card,
      pan_image,
      blood_group,
      parment_address,
      parment_city,
      parment_state,
      parment_country,
      current_address,
      current_city,
      current_state,
      current_country,
      gender,
      is_sickleave,
      meritial_status ,
    },
    educationDetails: {
      degree,
      board,
      percentage,
      passingyear,
      degreephotoes,
    },
    experienceDetails: { companyname, startdate, enddate, role },

    projectDetails: {
      projectName,
      technology,
      projectStartDate,
      projectEndDate,
      projectRole,
      responsibility,
    },

    bankDetails: { accountNumber, bankName, ifscCode, },
  },
} = EmpFormModel;

export const formInitialValue = {
  
  basicDetails: {
    [name.name]: "",
    [username.name]: "",
    [designation.name]: "",
    [emp_id.name]: "",
    [date_of_joining.name]: "",
    [image.name]: null,
    [mobile.name]: "",
    [email.name]: "",
    [password.name]:"",
    [company_email.name]: "",
    [company_email_password.name]: "",
    [skype_account.name]: "",
    [skype_password.name]: "",
    [home_number.name]: "",
    [assign_role.name]: "",
    [date_of_birth.name]: "",
    [aadhar_card.name]: "",
    [aadhar_image.name]: null,
    [aadhar_image_back.name]: null,
    [pan_card.name]: "",
    [pan_image.name]: null,
    [blood_group.name]: "",
    [gender.name]: "",
    [is_sickleave.name]: "",
    [meritial_status.name]: "",
    [current_address.name]: "",
    [current_city.name]: "",
    [current_state.name]: "",
    [current_country.name]: "",
    [parment_address.name]: "",
    [parment_city.name]: "",
    [parment_state.name]: "",
    [parment_country.name]: "",
  },
  educationDetails: [
    {
      [degree.name]: "",
      [board.name]: "",
      [percentage.name]: "",
      [passingyear.name]: "",
      [degreephotoes.name]: "",
    },
  ],
  experienceDetails: [
    {
      [companyname.name]: "",
      [startdate.name]: "",
      [enddate.name]: "",
      [role.name]: "",
    }
  ],
  projectDetails: [
    {
      [projectName.name]: "",
      [technology.name]: "",
      [projectStartDate.name]: "",
      [projectEndDate.name]: "",
      [projectRole.name]: "",
      [responsibility.name]: "",
    }
  ],
  bankDetails: {
    [accountNumber.name]: "",
    [bankName.name]: "",
    [ifscCode.name]: "",
    // [branchName.name]: "",
  },
};
