export const EMPLOYEE_LIST="EMPLOYEE_LIST" 
export const EMPLOYEE_BY_ID="EMPLOYEE_BY_ID" 

export const EMPLOYEE_LIST_REQUEST="EMPLOYEE_LIST_REQUEST"
export const EMPLOYEE_LIST_SUCCESS="EMPLOYEE_LIST_SUCCESS"
export const EMPLOYEE_LIST_FAILURE="EMPLOYEE_LIST_FAILURE"