export const ADD_TIMESHEET="ADD_TIMESHEET"
export const ADD_OVERTIME="ADD_OVERTIME"

export const ADD_TIMESHEET_REQUEST="ADD_TIMESHEET_REQUEST"
export const ADD_TIMESHEET_SUCCESS="ADD_TIMESHEET_SUCCESS"
export const ADD_TIMESHEET_FAILURE="ADD_TIMESHEET_FAILURE"


export const ADD_OVERTIME_REQUEST="ADD_OVERTIME_REQUEST"
export const ADD_OVERTIME_SUCCESS="ADD_OVERTIME_SUCCESS"
export const ADD_OVERTIME_FAILURE="ADD_OVERTIME_FAILURE"