export const EDIT_HOLIDAYS="EDIT_HOLIDAYS"

export const EDIT_HOLIDAYS_REQUEST="EDIT_HOLIDAYS_REQUEST"
export const EDIT_HOLIDAYS_SUCCESS="EDIT_HOLIDAYS_SUCCESS"
export const EDIT_HOLIDAYS_FAILURE="EDIT_HOLIDAYS_FAILURE"