export const OVER_TIME_LIST="OVER_TIME_LIST"

export const OVER_TIME_LIST_REQUEST="OVER_TIME_LIST_REQUEST"
export const OVER_TIME_LIST_SUCCESS="OVER_TIME_LIST_SUCCESS"
export const OVER_TIME_LIST_FAILURE="OVER_TIME_LIST_FAILURE"