export const ADD_CLIENTS="ADD_CLIENTS"

export const ADD_CLIENTS_REQUEST="ADD_CLIENTS_REQUEST"
export const ADD_CLIENTS_SUCCESS="ADD_CLIENTS_SUCCESS"
export const ADD_CLIENTS_FAILUER="ADD_CLIENTS_FAIUER"