export const HOLIDAY_LIST="HOLIDAY_LIST"

export const HOLIDAY_LIST_REQUEST="HOLIDAY_LIST_REQUEST"
export const HOLIDAY_LIST_SUCCESS="HOLIDAY_LIST_SUCCESS"
export const HOLIDAY_LIST_FAILUER="HOLIDAY_LIST_FAILUER"