export const VIEW_TIMESHEET="VIEW_TIMESHEET"

export const VIEW_TIMESHEET_REQUEST="VIEW_TIMESHEET_REQUEST"
export const VIEW_TIMESHEET_SUCCESS="VIEW_TIMESHEET_SUCCESS"
export const VIEW_TIMESHEET_FAILURE="VIEW_PROJECTS_LIST_FAILURE"